# Generated by Django 5.1 on 2024-08-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id_agencia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_agencia', models.CharField(max_length=255)),
                ('num_agencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cartao', models.AutoField(primary_key=True, serialize=False)),
                ('banco_cartao', models.CharField(max_length=255)),
                ('num_cartao', models.CharField(max_length=255)),
                ('cliente_cartao', models.CharField(max_length=255)),
                ('venc_cartao', models.CharField(max_length=255)),
                ('cv_cartao', models.CharField(max_length=255)),
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.DO_NOTHING, to='cartaoApp.agencia')),
                ('id_funcao', models.ForeignKey(db_column='id_funcao', on_delete=django.db.models.deletion.DO_NOTHING, to='cartaoApp.funcao')),
            ],
        ),
    ]
