# Generated by Django 5.1 on 2024-10-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validar',
            fields=[
                ('id_validar', models.AutoField(primary_key=True, serialize=False)),
                ('cartao_validar', models.CharField(max_length=255)),
                ('cpf_validar', models.CharField(max_length=255)),
                ('nome_validar', models.CharField(max_length=255)),
                ('codigo_validar', models.CharField(max_length=255)),
                ('data_validar', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='id_agencia',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='id_funcao',
        ),
        migrations.DeleteModel(
            name='Agencia',
        ),
        migrations.DeleteModel(
            name='Cartao',
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
    ]
